# Generated by Django 4.1.5 on 2023-01-18 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0002_accounttype_person_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='dob',
            field=models.DateField(default='2000-04-12'),
            preserve_default=False,
        ),
    ]
