# Generated by Django 4.1.5 on 2023-01-18 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0003_person_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='is_chequebook',
            field=models.BooleanField(default=False, verbose_name='Cheque Book'),
        ),
        migrations.AddField(
            model_name='person',
            name='is_creditcard',
            field=models.BooleanField(default=False, verbose_name='Credit Card'),
        ),
        migrations.AddField(
            model_name='person',
            name='is_debitcard',
            field=models.BooleanField(default=False, verbose_name='Debit Card'),
        ),
    ]
